<?php

/**
 * Load composer dependencies.
 */
require_once WP_CONTENT_DIR . '/vendor/autoload.php';


/**
 * Load extended functions.
 */
require_once get_template_directory() . '/inc/idkomm_functions.php';


/**
 * Include custom actions and filters.
 */
require_once get_template_directory() . '/inc/_actions.php';
require_once get_template_directory() . '/inc/_filters.php';
if (file_exists( get_template_directory() . '/inc/_customizer.php' )) {
	require_once get_template_directory() . '/inc/_customizer.php';
}
if (file_exists( get_template_directory() . '/inc/_colours.php' )) {
	require_once get_template_directory() . '/inc/_colours.php';
}


/**
 * Include Timber specific settings.
 */
require_once get_template_directory() . '/inc/_timber.php';


/**
 * Initialize Timber
 */
$timber = new \Timber\Timber( );

/* CPT */

function cptui_register_my_cpts() {

	/**
	 * Post Type: Recipes.
	 */

	$labels = [
		"name" => __( "Recipes", "custom-post-type-ui" ),
		"singular_name" => __( "Recipe", "custom-post-type-ui" ),
		"menu_name" => __( "My Recipes", "custom-post-type-ui" ),
		"all_items" => __( "All Recipes", "custom-post-type-ui" ),
		"add_new" => __( "Add new", "custom-post-type-ui" ),
		"add_new_item" => __( "Add new Recipe", "custom-post-type-ui" ),
		"edit_item" => __( "Edit Recipe", "custom-post-type-ui" ),
		"new_item" => __( "New Recipe", "custom-post-type-ui" ),
		"view_item" => __( "View Recipe", "custom-post-type-ui" ),
		"view_items" => __( "View Recipes", "custom-post-type-ui" ),
		"search_items" => __( "Search Recipes", "custom-post-type-ui" ),
		"not_found" => __( "No Recipes found", "custom-post-type-ui" ),
		"not_found_in_trash" => __( "No Recipes found in trash", "custom-post-type-ui" ),
		"parent" => __( "Parent Recipe:", "custom-post-type-ui" ),
		"featured_image" => __( "Featured image for this Recipe", "custom-post-type-ui" ),
		"set_featured_image" => __( "Set featured image for this Recipe", "custom-post-type-ui" ),
		"remove_featured_image" => __( "Remove featured image for this Recipe", "custom-post-type-ui" ),
		"use_featured_image" => __( "Use as featured image for this Recipe", "custom-post-type-ui" ),
		"archives" => __( "Recipe archives", "custom-post-type-ui" ),
		"insert_into_item" => __( "Insert into Recipe", "custom-post-type-ui" ),
		"uploaded_to_this_item" => __( "Upload to this Recipe", "custom-post-type-ui" ),
		"filter_items_list" => __( "Filter Recipes list", "custom-post-type-ui" ),
		"items_list_navigation" => __( "Recipes list navigation", "custom-post-type-ui" ),
		"items_list" => __( "Recipes list", "custom-post-type-ui" ),
		"attributes" => __( "Recipes attributes", "custom-post-type-ui" ),
		"name_admin_bar" => __( "Recipe", "custom-post-type-ui" ),
		"item_published" => __( "Recipe published", "custom-post-type-ui" ),
		"item_published_privately" => __( "Recipe published privately.", "custom-post-type-ui" ),
		"item_reverted_to_draft" => __( "Recipe reverted to draft.", "custom-post-type-ui" ),
		"item_scheduled" => __( "Recipe scheduled", "custom-post-type-ui" ),
		"item_updated" => __( "Recipe updated.", "custom-post-type-ui" ),
		"parent_item_colon" => __( "Parent Recipe:", "custom-post-type-ui" ),
	];

	$args = [
		"label" => __( "Recipes", "custom-post-type-ui" ),
		"labels" => $labels,
		"description" => "",
		"public" => true,
		"publicly_queryable" => true,
		"show_ui" => true,
		"show_in_rest" => true,
		"rest_base" => "",
		"rest_controller_class" => "WP_REST_Posts_Controller",
		"has_archive" => true,
		"show_in_menu" => true,
		"show_in_nav_menus" => true,
		"delete_with_user" => false,
		"exclude_from_search" => false,
		"capability_type" => "post",
		"map_meta_cap" => true,
		"hierarchical" => false,
		"rewrite" => [ "slug" => "recipes", "with_front" => true ],
		"query_var" => true,
		"supports" => [ "title", "custom-fields" ],
	];

	register_post_type( "recipes", $args );

	/**
	 * Post Type: Products.
	 */

	$labels = [
		"name" => __( "Products", "custom-post-type-ui" ),
		"singular_name" => __( "Product", "custom-post-type-ui" ),
		"menu_name" => __( "My Products", "custom-post-type-ui" ),
		"all_items" => __( "All Products", "custom-post-type-ui" ),
		"add_new" => __( "Add new", "custom-post-type-ui" ),
		"add_new_item" => __( "Add new Product", "custom-post-type-ui" ),
		"edit_item" => __( "Edit Product", "custom-post-type-ui" ),
		"new_item" => __( "New Product", "custom-post-type-ui" ),
		"view_item" => __( "View Product", "custom-post-type-ui" ),
		"view_items" => __( "View Products", "custom-post-type-ui" ),
		"search_items" => __( "Search Products", "custom-post-type-ui" ),
		"not_found" => __( "No Products found", "custom-post-type-ui" ),
		"not_found_in_trash" => __( "No Products found in trash", "custom-post-type-ui" ),
		"parent" => __( "Parent Product:", "custom-post-type-ui" ),
		"featured_image" => __( "Featured image for this Product", "custom-post-type-ui" ),
		"set_featured_image" => __( "Set featured image for this Product", "custom-post-type-ui" ),
		"remove_featured_image" => __( "Remove featured image for this Product", "custom-post-type-ui" ),
		"use_featured_image" => __( "Use as featured image for this Product", "custom-post-type-ui" ),
		"archives" => __( "Product archives", "custom-post-type-ui" ),
		"insert_into_item" => __( "Insert into Product", "custom-post-type-ui" ),
		"uploaded_to_this_item" => __( "Upload to this Product", "custom-post-type-ui" ),
		"filter_items_list" => __( "Filter Products list", "custom-post-type-ui" ),
		"items_list_navigation" => __( "Products list navigation", "custom-post-type-ui" ),
		"items_list" => __( "Products list", "custom-post-type-ui" ),
		"attributes" => __( "Products attributes", "custom-post-type-ui" ),
		"name_admin_bar" => __( "Product", "custom-post-type-ui" ),
		"item_published" => __( "Product published", "custom-post-type-ui" ),
		"item_published_privately" => __( "Product published privately.", "custom-post-type-ui" ),
		"item_reverted_to_draft" => __( "Product reverted to draft.", "custom-post-type-ui" ),
		"item_scheduled" => __( "Product scheduled", "custom-post-type-ui" ),
		"item_updated" => __( "Product updated.", "custom-post-type-ui" ),
		"parent_item_colon" => __( "Parent Product:", "custom-post-type-ui" ),
	];

	$args = [
		"label" => __( "Products", "custom-post-type-ui" ),
		"labels" => $labels,
		"description" => "",
		"public" => true,
		"publicly_queryable" => true,
		"show_ui" => true,
		"show_in_rest" => true,
		"rest_base" => "",
		"rest_controller_class" => "WP_REST_Posts_Controller",
		"has_archive" => true,
		"show_in_menu" => true,
		"show_in_nav_menus" => true,
		"delete_with_user" => false,
		"exclude_from_search" => false,
		"capability_type" => "post",
		"map_meta_cap" => true,
		"hierarchical" => false,
		"rewrite" => [ "slug" => "products", "with_front" => true ],
		"query_var" => true,
		"supports" => [ "title", "custom-fields" ],
	];

	register_post_type( "products", $args );
}

add_action( 'init', 'cptui_register_my_cpts' );


/* ACF Fields */

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5f5fd9744914d',
		'title' => 'Add Product',
		'fields' => array(
			array(
				'key' => 'field_5f61c460ee015',
				'label' => 'Product Image',
				'name' => 'product_image',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5f61c47aee016',
				'label' => 'Product Title',
				'name' => 'product_title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5f61c490ee017',
				'label' => 'Product Excerpt',
				'name' => 'product_excerpt',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5f620c15c0ae1',
				'label' => 'Product Info',
				'name' => 'product_info',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5f620c3cc0ae2',
				'label' => 'Product Ingredients',
				'name' => 'product_ingredients',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_5f620dd7cbf56',
						'label' => 'Ingredient',
						'name' => 'ingredient',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
			array(
				'key' => 'field_5f620c5ac0ae3',
				'label' => 'Product Size',
				'name' => 'product_size',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5f620c6ac0ae4',
				'label' => 'Product Origin',
				'name' => 'product_origin',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'products',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_5f5f8dd25b774',
		'title' => 'Add Recipe',
		'fields' => array(
			array(
				'key' => 'field_5f6084a82449c',
				'label' => 'Recipe Title',
				'name' => 'recipe_title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5f608c482fb4a',
				'label' => 'Recipe Excerpt',
				'name' => 'recipe_excerpt',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5f608c572fb4b',
				'label' => 'Recipe Image',
				'name' => 'recipe_image',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5f609f7fbc930',
				'label' => 'Recipe ingredients',
				'name' => 'recipe_ingredients',
				'type' => 'repeater',
				'instructions' => 'Klick on add row to add more ingredients',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_5f60a04dbc932',
						'label' => 'ingredient',
						'name' => 'ingredient',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
			array(
				'key' => 'field_5f620cd82b74f',
				'label' => 'Recipe Time',
				'name' => 'recipe_time',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5f620cf72b750',
				'label' => 'Recipe Portions',
				'name' => 'recipe_portions',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5f620d132b751',
				'label' => 'Recipe Instructions',
				'name' => 'recipe_instructions',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_5f620da85ff9f',
						'label' => 'Instruction',
						'name' => 'instruction',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
			array(
				'key' => 'field_5f620d562b752',
				'label' => 'Recipe Serve',
				'name' => 'recipe_serve',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'recipes',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_5f5f5f2eadf81',
		'title' => 'Mackays Layout',
		'fields' => array(
			array(
				'key' => 'field_5f5f5f810004d',
				'label' => 'Flexible Content',
				'name' => 'flexible_content',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layouts' => array(
					'layout_5f5f5f86e2249' => array(
						'key' => 'layout_5f5f5f86e2249',
						'name' => 'header_layout',
						'label' => 'Header Layout',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5f5f5fbb0004e',
								'label' => 'Header Image',
								'name' => 'header_image',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'full',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_5f61d142091fa' => array(
						'key' => 'layout_5f61d142091fa',
						'name' => 'slider',
						'label' => 'Slider',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5f61d15f091fb',
								'label' => 'Image 1',
								'name' => 'image_1',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'medium',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_5f61d16b091fc',
								'label' => 'Image 2',
								'name' => 'image_2',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'medium',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_5f61d178091fd',
								'label' => 'Image 3',
								'name' => 'image_3',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'medium',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_5f61d19aa96e6' => array(
						'key' => 'layout_5f61d19aa96e6',
						'name' => 'titles',
						'label' => 'Titles',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5f61d1a9a96e7',
								'label' => 'Product title',
								'name' => 'product_title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => 'Products',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5f61d1d6a96e8',
								'label' => 'Recipe title',
								'name' => 'recipe_title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => 'Recipes',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
				),
				'button_label' => '',
				'min' => '',
				'max' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'default',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	endif;
